version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "13:00" # 9am ET
      timezone: America/New_York
    assignees: [sjnims]
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 5
    groups:
      dev-deps:
        dependency-type: development
        update-types: [minor, patch]
      prod-deps:
        dependency-type: production
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "13:00"
      timezone: America/New_York
    assignees: [sjnims]
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 5
    groups:
      actions:
        update-types: [minor, patch]
